use-grammars = { except = [ "yaml", "json" ] }

[[language]]
name = "rust"

[language-server.rust-analyzer.config]
procMacro = { ignored = { leptos_macro = ["server"] } }

[language-server.rust-analyzer.config.check]
command = "clippy"


[[language]]
name = "go"

[language-server.gopls]
config = { "formatting.gofumpt" = true, "ui.diagnostic.staticcheck" = true, "analyses" = { "fieldalignment" = true, "nilness" = true } }


[[language]]
name = "markdown"
language-servers = [ "marksman", "ltex-ls"]
file-types = ["md"]
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}

[[language]]
name = "latex"
language-servers = [ "ltex-ls" ]
file-types = ["tex"]
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}
