[[language]]
name = "markdown"
language-server = { command = "ltex-ls" }
config = {}

[[language]]
name = "python"
# roots = ["pyproject.toml"]
# language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {} # <- this is the important line


[[language]]
name = "rust"

[language.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "go"
config = { "analyses" = { "fieldalignment" = true } }

[[language]]
name = "javascript"
language-server = { command = "typescript-language-server" }
config = {}

[[language]]
name = "c"
language-server = { command = "clangd" }
config = {}

[[language]]
name = "cpp"
language-server = { command = "clangd" }
config = {}

[[language]]
name = "yaml"
config = {}

[[language]]
name = "lua"
language-server = { command = "/home/cliang/.local/share/nvim/mason/bin/lua-language-server" }
config = {}
