[[language]]
name = "markdown"
language-server = { command = "ltex-ls" }

[[language]]
name = "python"
roots = ["pyproject.toml"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {} # <- this is the important line

[[language]]
name = "rust"

[language.config]
checkOnSave = { command = "clippy" }