use-grammars = { except = [ "yaml", "json" ] }

[[language]]
name = "rust"

[language-server.rust-analyzer.config]
procMacro = { ignored = { leptos_macro = ["server"] } }

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "markdown"
language-servers = [ "marksman", "ltex-ls" ]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }
