syntax on
" filetype plugin on
filetype plugin indent on

set nocompatible
set number
set tabstop=4
set softtabstop=0
set shiftwidth=4
set expandtab
set path+=**
set wildmenu
set ruler
set mouse=a
set mousemodel=popup
set t_Co=256
set guioptions=egmrti
set gfn=Monospace\ 10
set autowrite

" set makeprg=bundle\ exec\ rspec\ -f\ QuickfixFormatter

colorscheme habamax

" May need for Vim (not Neovim) since coc.nvim calculates byte offset by count
" utf-8 byte sequence
set encoding=utf-8
" Some servers have issues with backup files, see #649
set nobackup
set nowritebackup

" Having longer updatetime (default is 4000 ms = 4s) leads to noticeable
" delays and poor user experience
set updatetime=300

" Always show the signcolumn, otherwise it would shift the text each time
" diagnostics appear/become resolved
set signcolumn=yes

let g:indentLine_enabled = 1
let g:indentLine_concealcursor = ''
let g:indentLine_char = '┆'
let g:indentLine_faster = 1

let g:airline_powerline_fonts = 1

fun! TrimWhitespace()
    let l:save = winsaveview()
    keeppatterns %s/\s\+$//e
    call winrestview(l:save)
endfun
autocmd BufWritePre * call TrimWhitespace()

" ========== key mappings =========== "
let mapleader="\\"

" Move blocks up and down
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

" Keep curser in the same position
nnoremap J mzJ`z

" Keey curser in the same position during move
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz

" Paste over the highlighted word with copied word
xnoremap <Leader>p "\"_dP

" Keep curser during search
nnoremap n nzzzv
nnoremap N Nzzzv

hi Function guifg='#61afef'
hi Comment guifg='#5c6370'
hi Normal guifg='#abb2bf' guibg='#282c34'
hi Constant guifg='#d19a66'
hi Statement guifg='#c678dd'
hi Keyword guifg='#c678dd'
hi Conditional guifg='#c678dd'
hi Operator guifg='silver'
hi Exception gui=bold guifg='silver'
hi Label guifg='silver'
hi Repeat guifg='#c678dd'
hi Type guifg='#e5c07b'
hi PreCondit guifg='#c678dd'
hi Include guifg='#c678dd'
hi Macro guifg='silver'
hi String guifg='#98c379'
hi SpecialChar guifg='#e06c75'
hi SpecialComment guifg='green'

autocmd BufRead,BufNewFile *.go match goFunctionName '\<\h\w*\ze\_s\{-}(\%(\*\h\w*)\_s\{-}(\)\@!'
autocmd BufRead,BufNewFile *.zig match cppFunctionName '\<\h\w*\ze\_s\{-}(\%(\*\h\w*)\_s\{-}(\)\@!'

hi def link zigFunctionName Function
hi def link goFunctionName Function
